version: '3'
services:
  webserver:
    build:
      context: .
      args:
        AIRFLOW_ADMIN_PASSWORD: ${AIRFLOW_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    
    depends_on:
      - postgres
  scheduler:
    build:
      context: .
      args:
        AIRFLOW_ADMIN_PASSWORD: ${AIRFLOW_ADMIN_PASSWORD}
    command: airflow scheduler
    depends_on:
      - postgres
      - webserver
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: "airflow"
      POSTGRES_PASSWORD: ${pg_password}
      POSTGRES_DB: "airflow"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
