name: "spotify_wrapped"
version: "1.0.0"
config-version: 2

profile: "spotify_wrapped"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

packages:
  - package: test_macros
    version: 0.1.0
    git: "git@github.com:Kevin-Nduati/My-Spotify-Wrapped.git"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  spotify_wrapped:
    # Config indicated by + and applies to all files under models/example/
