# I will define a simple workflow using Super-Linter. The end goal of this tool is:
# * Prevent broken code from being uploaded to the default branch
# * Help establish best practices across multiple languages
# * Build guidelines for code layout and format
# * Automate the process to help streamline code reviews

# For more information: https://github.com/marketplace/actions/super-linter


name: Super-Linter


on: 
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_FLAKE8: "false"

